const WINDOW_WIDTH = 810
const WINDOW_HEIGHT = 1440
const ENTITY_RADIUS = 5
const SPEED = 3
const DETECTION_RADIUS = 100
const CONVERSION_RADIUS = 20
const EDGE_AVOID_RADIUS = 50
const REPULSION_RADIUS = 20
const ICON_WIDTH = 30
const ICON_HEIGHT = 30

export {
  WINDOW_WIDTH,
  WINDOW_HEIGHT,
  ENTITY_RADIUS,
  SPEED,
  DETECTION_RADIUS,
  CONVERSION_RADIUS,
  EDGE_AVOID_RADIUS,
  REPULSION_RADIUS,
  ICON_WIDTH,
  ICON_HEIGHT,
}
